### ISSUE TITLE
setup project

### ISSUE THREAD

**Issue by kaczor6418** [GDSC-Lodz-University-of-Technology/warzywniax#1]
Set up project with:

- [x] [eslint](https://eslint.org/)
- [x] [pretttier](https://prettier.io/)
- [x] [react](https://reactjs.org/)
- [x] [typescript](https://www.typescriptlang.org/)
- [x] [react router](https://reactrouter.com/en/main)
- [x] [tanstack-query](https://tanstack.com/query/latest)
- [x] [vite](https://vitejs.dev/)
- [x] [firebase](https://firebase.google.com/)
- [x] [react material ui](https://mui.com/)
- [x] [react-hook-form](https://react-hook-form.com/)
- [x] [git-hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)
- [x] [i18n](https://react.i18next.com/)
- [x] [google maps api](https://developers.google.com/maps/documentation/javascript/overview)

**Comment by HKGx** [comment]
Overall a good stack, but:
- [*Tanstack Router*](https://github.com/tanstack/router) sounds good, but it's too young in its development, IMO. They don't support anything other than basic *react-dom*.
- [*Formik*](https://github.com/jaredpalmer/formik), I had some commercial experience with it. It quickly grew too much and was hell to maintain, we decided to change it to [*react-hook-form*](https://github.com/react-hook-form/react-hook-form). There is a good comparison: https://blog.logrocket.com/react-hook-form-vs-formik-comparison/. But in my experience *react-hook-form* is faster, easier to use with TypeScript, and easier to build forms with. Over the course of 2022, _formik_ was even superseded by _react-hook-forms_ in the downloads count on NPM.

**Comment by kaczor6418** [comment]
[Tanstack Router](https://github.com/tanstack/router) dependency is not synchronized with its documentation, what makes is very hard to use. I have decided to use [react-router](https://reactrouter.com/en/main) instead
